### ISSUE TITLE
Method to select coordinates of given chain or group

### ISSUE THREAD

**Issue by tomnewport** [rcsb/mmtf-python#24]
I would like to be able to get a list of atom indices for a given chain ID. This is necessary for building biological assemblies. Currently, I am using the following code to assemble arrays with elements for each atom and indices of groups and chains, but it seems rather hacky. Is there a better way to do this, and if not, would this be useful to include?

```python
atom_group_ids = numpy.zeros(len(tf.x_coord_list), dtype="I")
atom_chain_ids = numpy.zeros(len(tf.x_coord_list), dtype="I")

group_max = 0
group_in_chain = 0
current_chain = 0
for group_id, group_type in enumerate(tf.group_type_list):
    group_size = len(tf.group_list[group_type]["elementList"])
    atom_group_ids[group_max:group_max + group_size] = group_id
    atom_chain_ids[group_max:group_max + group_size] = current_chain
    group_max += group_size
    group_in_chain += 1
    if group_in_chain > tf.groups_per_chain[current_chain]:
        current_chain += 1
        group_in_chain = 0
```

Indices can then be obtained with:
```python
numpy.argwhere(atom_chain_ids == 6)[:,0]
```

**Comment by abradle** [comment]
I think you're approach looks good! We had a discussion - and think it's out of scope for the format to directly provide this data.
