### ISSUE TITLE
How can we download the entire PDB archive in mmtf format?

### ISSUE THREAD

**Issue by molecules** [rcsb/mmtf-python#26]
The slides at https://www.slideshare.net/YanaValasatava/cadd-meeting-08302016 mention analyzing the entire PDB in mmtf format. But how do you actually download the entire PDB in mmtf format?

**Comment by molecules** [comment]
It looks like we would need to download it as a Hadoop Sequence file, according to `http://mmtf.rcsb.org/download.html`. The full records would be in `http://mmtf.rcsb.org/v1.0/hadoopfiles/full.tar` and the reduced records would be in `http://mmtf.rcsb.org/v1.0/hadoopfiles/reduced.tar`. But I'm still trying to figure out how to operate on those files.

**Comment by pwrose** [comment]
We are working on a library that uses PySpark to read and process these
files in Python. We'll let you know when we have some basic functionality
available.

**Comment by abradle** [comment]
I'm going to close this as resolved by PySpark library.

**Comment by harryjubb** [comment]
@molecules I've had success in converting the all of the HSF `part-*` files into one big `tar.gz` file using [forqlift](http://qethanm.cc/projects/forqlift/).

    forqlift toarchive --file full.tgz full/part-*

You can also extract from individual `part-*` files directly, but would need to loop through them all to extract everything.

Will RCSB offer a more standard archive (such as `tgz`) for mirroring the PDB via MMTF in the future? The HSF files seem a bit unwieldy, and less helpful unless you're doing analysis on the whole archive.

**Comment by pwrose** [comment]
We'll discuss options after folks are back from summer vacation.

Can you describe your use case. Do you typically need 10s, 100s, 1000s of
files?

Do you want to download a single tgz with the all the individual files?
Would it be useful to have the mmtf.gz files available for download on an
FTP server? Then RSYNC could be used to keep a local copy up to date,
without downloading the whole archive.

Ideally, we'd like to provide an API so you don't need to worry how files
are delivered and local caching could be used to avoid repeated download of
the same files (we do this in the BioJava library).

**Comment by harryjubb** [comment]
Thanks for your reply, for me it's 1000s of files covering the human structural proteome or more. The nice thing about having everything in a single archive is that it's so much faster to download one big file than interrogating each individual file and optionally downloading; at least for the first download. It helps that MMTF is a lot smaller in any case! An API that takes care of some of that would be great.

**Comment by ncoish** [comment]
Was any progress ever made on this PySpark library?

**Comment by ncoish** [comment]
Using RSYNC to keep local copies updated without re-downloading would be very useful

**Comment by pwrose** [comment]
The mmtf-pyspark library is here:
https://github.com/sbl-sdsc/mmtf-pyspark

Check out the tutorial in mmtf-workshop-2018:
https://github.com/sbl-sdsc/mmtf-workshop-2018

mmt-genomics is a prototype application built on top of mmtf-pyspark:
https://github.com/sbl-sdsc/mmtf-genomics

I plan some upgrades to mmtf-pyspark later this year as some of the web
service calls need to be updated.
