### ISSUE TITLE
Please rename bin/sample to have a more project-specific name

### ISSUE THREAD

**Issue by yurivict** [rcsb/mmtf-python#42]
Otherwise, it might conflict with some other executables.
Or, maybe consider removing it altogether, because this behavior is not common for python packages.

**Comment by abradle** [comment]
Sorry I don’t quite understand what you mean?

**Comment by yurivict** [comment]
Please, do not install /usr/local/bin/sample.

**Comment by abradle** [comment]
Could you show me in the code where we reference bin/sample? Ideally a pull request would be great. Happy to help - still unclear what we’re doing wrong.

**Comment by yurivict** [comment]
Distutils installs 'bin/sample' because of these lines in ```setup.py```:

https://github.com/rcsb/mmtf-python/blob/master/setup.py#L106

```
    entry_points={
        'console_scripts': [
            'sample=sample:main',
        ],
    },
```

Installing the /usr/local/bin/sample executable can easily conflict with other packages.
Please either rename 'sample', or delete it altogether.

**Comment by abradle** [comment]
Thanks that’s awesome! And quite stupid from me. I’ll fix.

**Comment by abradle** [comment]
Done - thanks!
