### ISSUE TITLE
Python interface returns a wrong number of groups

### ISSUE THREAD

**Issue by yurivict** [rcsb/mmtf-python#47]
This testcase:
```
from mmtf import fetch

decoded_data = fetch("4NHO")

print("numGroups="+str(len(decoded_data.group_list)))
for i in range(0, len(decoded_data.group_list)-1):
    print(decoded_data.group_list[i]["groupName"])                                                                                                                                                                        
```
prints that there are 32 groups, when in reality ```4NHO``` has 488 residues (groups): https://www.rcsb.org/structure/4NHO

```
numGroups=32
SO4
ASN
VAL
LYS
CYS
HOH
HG
LEU
MET
PRO
GOL
HIS
ARG
ILE
GLY
GLU
GLU
ASP
TRP
GLN
TYR
PHE
THR
CXS
VAL
SER
THR
SER
GLN
ALA
CSO
```

Version ```py36-mmtf-python-1.1.2```.

**Comment by abradle** [comment]
Hi @yurivict thanks for your interest and question! 

That 32 number is the number of unique group descriptions. This would include residues, water and cofactors. 

An example group is below:
```
 {'groupName': 'SER',
  'atomNameList': ['N', 'CA', 'C', 'O', 'CB', 'OG'],
  'elementList': ['N', 'C', 'C', 'O', 'C', 'O'],
  'bondOrderList': [1, 1, 2, 1, 1],
  'bondAtomList': [1, 0, 2, 1, 3, 2, 4, 1, 5, 4],
  'formalChargeList': [0, 0, 0, 0, 0, 0],
  'singleLetterCode': 'S',
  'chemCompType': 'L-PEPTIDE LINKING'}
```
This describes the atom name and bond orders (etc) for every group of that type in the file. (This helps with compression). 

decoded_data.group_id_list is a list of all the residue ids in the file - going from 352 to 1220 as in the PDB file you link to.

An up to date specification for the file format is here: https://github.com/rcsb/mmtf

**Comment by yurivict** [comment]
Thank you.

------

Python interface isn't documented. This page only has a very simple example: https://rcsb.github.io/mmtf-python/docs/api/v1.0.0/
