### ISSUE TITLE
Fallback for missing description in entities.

### ISSUE THREAD

**Issue by zacharyrs** [rcsb/mmtf-python#51]
I've managed to create an `mmtf` with partial entity info data (via BioJava) - missing the description field.
Can we add a fallback [here](https://github.com/rcsb/mmtf-python/blob/c913a6fc0194e50a825e86d7584ae2bbad3c1d7d/mmtf/utils/decoder_utils.py#L156) to prevent crashes?

**Comment by zacharyrs** [comment]
If desired I can put up a PR - BioJava just uses "no name", so I could do that?

**Comment by pwrose** [comment]
Sure, how about just adding an empty string for the description field?
