### ISSUE TITLE
Fresh release to PyPI?

### ISSUE THREAD

**Issue by zacharyrs** [rcsb/mmtf-python#54]
Can we get a new release to PyPI - there are a few bugs fixed in `master`.

Specifically:
- https://github.com/rcsb/mmtf-python/issues/48
- https://github.com/rcsb/mmtf-python/pull/52

**Comment by pwrose** [comment]
v1.1.3 has been released on PyPi with the following changes:

- upgraded msgpack to >=1.0.0
- removed unused ipython dependency
- default entity description to empty string
- initialize title to None
